### ISSUE TITLE
While fixing issue 2, filter_peaks no longer works due to indexing of opposite swings added in issue 1

### ISSUE THREAD

**Issue by rocketpoweryul** [rocketpoweryul/TradeTronic#4]
**This code:**
```
    # loop through swing highs, starting at the second occurrence and ending at 2nd last occurrence given the rules
    for i in range( 1, len(swing_highs) - 1 ):
        prev_swing_high_price = df.loc[swing_highs[i-1], 'High']
        curr_swing_high_price = df.loc[swing_highs[i  ], 'High']
        next_swing_high_price = df.loc[swing_highs[i+1], 'High']
        next_swing_low_price  = df.loc[swing_lows[i+1],  'Low' ]
        
        # detect positive peak
        if ( curr_swing_high_price > prev_swing_high_price ) and \
           ( curr_swing_high_price > next_swing_high_price or prev_swing_high_price > next_swing_low_price):
            df.loc[swing_highs[i], 'Peak'] = 1
            
    # loop through swing lows, starting at the second occurrence and ending at 2nd last occurrence given the rules
    for i in range( 1, len(swing_lows) - 1 ):
        prev_swing_low_price  = df.loc[swing_lows[i-1], 'Low' ]
        curr_swing_low_price  = df.loc[swing_lows[i  ], 'Low' ]
        next_swing_low_price  = df.loc[swing_lows[i+1], 'Low' ]
        next_swing_high_price = df.loc[swing_highs[i+1], 'High']
```

**Creates this error:**
```
Traceback (most recent call last):
  File "c:\Users\admin\GitHub\TradeTronic\y_SysInt_Tests.py", line 28, in <module>
    df = filter_peaks(df)
  File "c:\Users\admin\GitHub\TradeTronic\TATools.py", line 161, in filter_peaks
    next_swing_low_price  = df.loc[swing_lows[i+1],  'Low' ]
IndexError: list index out of range
```

**Comment by rocketpoweryul** [comment]
### Root cause
The for loops index on one swing, so using that index for the other swing will not work.

The code will need to be a little more complex to find the adjacent other swing type.

**Comment by rocketpoweryul** [comment]
### Corrective Action

Swing highs must always precede swing lows and vice versa, there can never be two in a row of one type.
So assuming indexing was the same make sense superficially, but be dangerous in corner cases.

We must actively find the next opposite swing, if it exists and not assume its index.

**Pseudo code should be, assuming we are looping through swing highs:**
- find the next swing low to the right of the current swing high
- If it doesn't exist, set price to None
- check for not None, and detect the condition

**Comment by rocketpoweryul** [comment]
### Proposed Code

```
# loop through swing highs, starting at the second occurrence and ending at 2nd last occurrence given the rules
    for i in range( 1, len(swing_highs) - 1 ):
        prev_swing_high_price = df.loc[swing_highs[i-1], 'High']
        curr_swing_high_price = df.loc[swing_highs[i  ], 'High']
        next_swing_high_price = df.loc[swing_highs[i+1], 'High']
        
        # Find the index of the next swing low after the current swing high
        next_swing_low_indices = [low for low in swing_lows if low > swing_highs[i]]
        next_swing_low_price = df.loc[next_swing_low_indices[0], 'Low'] if next_swing_low_indices else None
        
        # detect positive peak
         # Detect positive peak
        if curr_swing_high_price > prev_swing_high_price and \
          (curr_swing_high_price > next_swing_high_price or  \
           (next_swing_low_price is not None and prev_swing_high_price > next_swing_low_price)):
            df.loc[swing_highs[i], 'Peak'] = 1
            
    # loop through swing lows, starting at the second occurrence and ending at 2nd last occurrence given the rules
    for i in range( 1, len(swing_lows) - 1 ):
        prev_swing_low_price  = df.loc[swing_lows[ i-1], 'Low' ]
        curr_swing_low_price  = df.loc[swing_lows[ i  ], 'Low' ]
        next_swing_low_price  = df.loc[swing_lows[ i+1], 'Low' ]
        
        # find the index of the next swing high after the current swing low
        next_swing_high_indices = [high for high in swing_highs if high > swing_lows[i]]
        next_swing_high_price = df.loc[next_swing_high_indices[0], 'High'] if next_swing_high_indices else None

        # Detect negative peak
        if curr_swing_low_price < prev_swing_low_price and \
           (curr_swing_low_price < next_swing_low_price or \
            (next_swing_high_price is not None and prev_swing_low_price < next_swing_high_price)):
            df.loc[swing_lows[i], 'Peak'] = -1
```

This cleans up the error but not indexing blindly. Error no longer occurs
